---
title: "Introduction"
format:
  html: default
  pdf: default
editor: visual
execute: 
  echo: true
bibliography: references.bib
---

## Motivation

Evidence-based practice (EBP) is a healthcare approach in which professionals utilize the most reliable and relevant information to make clinical decisions tailored to individual patients [@mckibbon1998]. Effective EBP takes time and energy and involves five steps. The most important one is the second step, which is the retrieval of the necessary information to answer the questions. This can involve textbooks or a laboratory test but often requires the use of the journal literature. However, the different terms used can cause confusion and prevent people from fully understanding the potential of these review types. Our main goal here is to provide insight into the most common types of reviews, including [narrative reviews](narrative_reviews.qmd), [systematic reviews](systematic_reviews.qmd), [scoping reviews](scoping_reviews.qmd), [rapid reviews](rapid_reviews.qmd) and [umbrella reviews](umbrella_reviews.qmd).
